"use client";

import "./globals.css";
import { Inter } from "next/font/google";

import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
} from "@web3modal/ethereum";
import { Web3Modal } from "@web3modal/react";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import { arbitrum, mainnet, polygon, Chain, sepolia } from "wagmi/chains";

const localnet: Chain = {
  id: 31337,
  name: "Localnet",
  nativeCurrency: {
    name: "Localnet Ethereum",
    symbol: "TestETH",
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ["http://127.0.0.1:8545/"],
    },
    public: {
      http: ["http://127.0.0.1:8545/"],
    },
  },
  network: "localhost",
};

const chains = [arbitrum, mainnet, polygon, localnet, sepolia];
const projectId = "65fc79d08d3ded2d18254b7c46068d10";

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })]);
const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: w3mConnectors({ projectId, chains }),
  publicClient,
});
const ethereumClient = new EthereumClient(wagmiConfig, chains);

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiConfig config={wagmiConfig}>{children}</WagmiConfig>

        <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
      </body>
    </html>
  );
}
